### PR TITLE
Changing name of Wookie to the correct spelling of Wookiee. Had to touch

### PR DESCRIPTION
**Pull request by Crashfreak**
a lot of files due to folder name changes

Sorry so many files had to change, but changing so many folders and little string values all over the place causes that.

@pcross616 check it out. We will have to change all the build dependency things from Wookie to Wookiee as well. And would be nice to rename the repo as well.

### CODE REVIEW

**Comment by pcross616** [comment]
Seems the tests are still failing.  Looks like the configs are wrong still.

**Comment by Crashfreak** [comment]
Strange seems like it might be related to Travis-CI, as my local builds are working correctly. I will try to look into it further, as I don't want this PR to hang around too long.

**Comment by pcross616** [comment]
i can re-kick the build to make sure it was not a fluke.

**Comment by Crashfreak** [comment]
Well seems like that actually worked, guess it was a fluke. I know that only until the last commit would it work correctly. So maybe it was not pulling the latest code.

**Comment by Crashfreak** [comment]
I will let you merge the PR, as there may be a couple of links that used to use wookie instead of wookiee that will need a little updating.

**Comment by pcross616** [comment]
Can you fix the kafka name change issue   there is a wookie-kafka along side wookiee-kafka @malibuworkcrew  @Crashfreak

**Pull request merged**
